---
- name: Installing Kafka on Ubuntu
  hosts: localhost
    #  vars:
    #    - dwnurl: https://downloads.apache.org/kafka/3.5.1/kafka_2.13-3.5.1.tgz
    #    - user: kafka
    #    - fpath: /home
    #    - installation_dir : /opt/kafka
    #    - buser: root
- hosts: localhost
  become: true
  roles: 
    - prerequisite

- hosts: localhost
  become: true
  roles: 
    - installation

- hosts: localhost
  become: true
  gather_facts: true
  roles: 
    - configuration

- hosts: localhost
  become: true
  gather_facts: false
  roles:
    - servers
