---
properties_by_nodes:
  - node_id: 1
    cqvoters: 1@web.example.com:8080,2@web.example.com:8081,3@web.example.com:8082
    listeners: SASL_SSL://web.example.com:18080,CONTROLLER://web.example.com:8080
    advertised: SASL_SSL://web.example.com:18080
    log_dir: /tmp/kafka/logs/server1/kraft-combined-logs

  - node_id: 2
    cqvoters: 1@web.example.com:8080,2@web.example.com:8081,3@web.example.com:8082
    listeners: SASL_SSL://web.example.com:18081,CONTROLLER://web.example.com:8081
    advertised: SASL_SSL://web.example.com:18081
    log_dir: /tmp/kafka/logs/server2/kraft-combined-logs

  - node_id: 3
    cqvoters: 1@web.example.com:8080,2@web.example.com:8081,3@web.example.com:8082
    listeners: SASL_SSL://web.example.com:18082,CONTROLLER://web.example.com:8082
    advertised: SASL_SSL://web.example.com:18082
    log_dir: /tmp/kafka/logs/server3/kraft-combined-logs

